### ISSUE TITLE
R3.8 No (Plot) file is produced after saving

### ISSUE THREAD

**Issue by zx8754** [oncogenetics/LocusExplorer#55]
No file is produced after saving: On my machine, after saving the file to a specific folder, there is no output file being produced. I tried with in multiple folders with multiple different file names.

**Comment by zx8754** [comment]
App was probably running within RStudio viewer. Application needs to run on an external web browser, e.g.: Chrome, IE, etc.

I could not replicate this error, closing this issue.

If error persists, suggest to re-open this issue.

**Comment by EdSaunders** [comment]
Identified the source of this issue as the shiny downloadHandler requiring Flash, which is not available within RStudio (e.g. https://github.com/rstudio/shiny/issues/623 and http://stackoverflow.com/questions/29286518/downloading-2-subset-files-in-r-shiny).
Amended launch instructions and code to use launch.browser = TRUE so that the app is run in an external browser by default rather than directly in RStudio.
